# Generated by Django 4.1.1 on 2022-09-27 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('correo', models.EmailField(max_length=100, verbose_name='Email')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('rol', models.CharField(choices=[('MEDICO', 'Med'), ('ENFERMER@', 'Enf'), ('PACIENTE', 'Pac'), ('FAMILIAR', 'Fam'), ('AUXILIAR', 'Aux')], default='PACIENTE', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=15, verbose_name='cargo')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_auxiliar', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_enfermero', to='shcApp.auxiliar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_enfermero', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_familiar', to='shcApp.auxiliar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_familiar', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profesion', models.CharField(max_length=15, verbose_name='profesion')),
                ('eps', models.CharField(max_length=30, verbose_name='eps')),
                ('nivel', models.IntegerField(default=0, verbose_name='nivel')),
                ('especialidad', models.CharField(max_length=30, verbose_name='especialidad')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_medico', to='shcApp.auxiliar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_medico', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eps', models.CharField(max_length=30, verbose_name='eps')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_paciente', to='shcApp.auxiliar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_Paciente', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='signosVitales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oximetria', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='oximetria')),
                ('saturacion', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='saturacion')),
                ('presion', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='presion')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='temperatura')),
                ('frecuencia_cardiaca', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='frecuencia_cardiaca')),
                ('frecuencia_respiratoria', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='frecuencia_cardiaca')),
                ('glicemia', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='glicemia')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('familiar_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_familiar_signosVitales', to='shcApp.familiar')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_signosVitales', to='shcApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medico_Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='fecha_inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha_fin')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_medico', to='shcApp.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_medico_medicoPaciente', to='shcApp.paciente')),
                ('registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_medico_paciente', to='shcApp.auxiliar')),
            ],
        ),
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('diagnostico_medico', models.CharField(max_length=250, verbose_name='diagnostico_medico')),
                ('sugerencia_cuidado', models.CharField(max_length=250, verbose_name='sugerencia_cuidado')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('familiar_consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_familiar_consulta', to='shcApp.familiar')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_historiaClinica', to='shcApp.paciente')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico_historiaClinica', to='shcApp.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar_Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='fecha_inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha_fin')),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_familiar_familiarPaciente', to='shcApp.familiar')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_familiarPaciente', to='shcApp.paciente')),
                ('id_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_familiar_paciente', to='shcApp.auxiliar')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero_Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='fecha_inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha_fin')),
                ('id_enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_enfermero_enfermeropaciente', to='shcApp.enfermero', unique=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_enfermeropaciente', to='shcApp.paciente', unique=True)),
                ('id_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_enfermero_paciente', to='shcApp.auxiliar')),
            ],
        ),
    ]
