# Generated by Django 4.1.1 on 2022-09-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shcApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='medico_consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_medico_consulta_signosVitales', to='shcApp.medico'),
        ),
    ]
