# Generated by Django 4.1.1 on 2022-09-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shcApp', '0002_signosvitales_medico_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='cargo'),
        ),
    ]
